version: '3'

services: 
    react:
        build:
            context: .
            dockerfile: Dockerfile
        ports: 
            - '0.0.0.0:8080:8080'
        volumes: 
            - .:/code
        network_mode: 'host'
